MvcTrgovac/MvcTrgovac/Controllers/ProdatiProizvodiUController.cs
using MvcTrgovac.Models;
using MvcTrgovac.Repository.IRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace MvcTrgovac.Controllers
{
    public class ProdatiProizvodiUController : Controller
    {
        private readonly IProdatiProizvodiURepository _prodatiProizvodiURepository;

        public ProdatiProizvodiUController(IProdatiProizvodiURepository prodatiProizvodiURepository)
        {
            this._prodatiProizvodiURepository = prodatiProizvodiURepository;
        }

        // GET: ProdatiProizvodiU
        public ActionResult Index(string sortOrder, string currentFilter, int? page, string searchString, string SifraVDP, string SifraRM, string SifraJM, string KolicinaProdatihPP, string KolicinaProdatihDP, string KolicinaProdatihU)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.SvdpSortParm = String.IsNullOrEmpty(sortOrder) ? "svdp_desc" : "";
            ViewBag.SrmSortParm = sortOrder == "srm_asc" ? "srm_desc" : "srm_asc";
            ViewBag.SjmSortParm = sortOrder == "sjm_asc" ? "sjm_desc" : "sjm_asc";
            ViewBag.SprodPSortParm = sortOrder == "sprodp_asc" ? "sprodp_desc" : "sprodp_asc";
            ViewBag.SprodDSortParm = sortOrder == "sprodd_asc" ? "sprodd_desc" : "sprodd_asc";
            ViewBag.SprodUSortParm = sortOrder == "sprodu_asc" ? "sprodu_desc" : "sprodu_asc";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            IQueryable<MasterModel> result = this._prodatiProizvodiURepository.GetAll(searchString, SifraVDP, SifraRM, SifraJM, KolicinaProdatihPP, KolicinaProdatihDP, KolicinaProdatihU);

            switch (sortOrder)
            {
                case "svdp_desc":
                    result = result.OrderByDescending(s => s.SifraVDP);
                    break;
                case "srm_asc":
                    result = result.OrderBy(s => s.SifraRM);
                    break;
                case "srm_desc":
                    result = result.OrderByDescending(s => s.SifraRM);
                    break;
                case "sjm_asc":
                    result = result.OrderBy(s => s.SifraJM);
                    break;
                case "sjm_desc":
                    result = result.OrderByDescending(s => s.SifraJM);
                    break;
                case "sprodp_asc":
                    result = result.OrderBy(s => s.KolicinaProdatihPP);
                    break;
                case "sprodp_desc":
                    result = result.OrderByDescending(s => s.KolicinaProdatihPP);
                    break;
                case "sprodd_asc":
                    result = result.OrderBy(s => s.KolicinaProdatihPP);
                    break;
                case "sprodd_desc":
                    result = result.OrderByDescending(s => s.KolicinaProdatihPP);
                    break;
                case "sprodu_asc":
                    result = result.OrderBy(s => s.KolicinaProdatihPP);
                    break;
                case "sprodu_desc":
                    result = result.OrderByDescending(s => s.KolicinaProdatihPP);
                    break;
                default:  // Name ascending 
                    result = result.OrderBy(s => s.SifraVDP);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(result.ToPagedList(pageNumber, pageSize));
        }

        // GET: ProdatiProizvodiU/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProdatiProizvodiU/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SifraVDP,SifraRM,SifraJM,KolicinaProdatihPP,KolicinaProdatihDP")] MasterModel masterModel)
        {
            if (ModelState.IsValid)
            {
                this._prodatiProizvodiURepository.Create(masterModel);
                return RedirectToAction("Index");
            }
            return View(masterModel);
        }

        // GET: ProdatiProizvodiU/Edit/id
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MasterModel prodatiProizU = this._prodatiProizvodiURepository.GetById((int)id);
            if (prodatiProizU == null)
            {
                return HttpNotFound();
            }
            return View(prodatiProizU);
        }

        // POST: ProdatiProizvodiU/Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MasterModel masterModel)
        {
            if (ModelState.IsValid)
            {
                this._prodatiProizvodiURepository.Edit(masterModel);
                return RedirectToAction("Index");
            }
            return View(masterModel);
        }

        // GET: ProdatiProizvodiU/Delete/id
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MasterModel kupljeniProizU = this._prodatiProizvodiURepository.GetById((int)id);
            if (kupljeniProizU == null)
            {
                return HttpNotFound();
            }
            return View(kupljeniProizU);
        }

        // POST: ProdatiProizvodiPP/Delete/id
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            this._prodatiProizvodiURepository.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this._prodatiProizvodiURepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcTrgovac/MvcTrgovac/Views/ProdatiProizvodiU/Create.cshtml
@model MvcTrgovac.Models.MasterModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Godišnji podaci o količini prodatih duvanskih proizvoda</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.SifraVDP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SifraVDP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SifraVDP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SifraRM, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SifraRM, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SifraRM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SifraJM, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SifraJM, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SifraJM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KolicinaProdatihPP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KolicinaProdatihPP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KolicinaProdatihPP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KolicinaProdatihDP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KolicinaProdatihDP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KolicinaProdatihDP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcTrgovac/MvcTrgovac/Views/ProdatiProizvodiU/Delete.cshtml
@model MvcTrgovac.Models.MasterModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Podaci o količini prodatih duvanskih proizvoda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SifraVDP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SifraVDP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SifraRM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SifraRM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SifraJM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SifraJM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KolicinaProdatihPP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KolicinaProdatihPP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KolicinaProdatihDP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KolicinaProdatihDP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KolicinaProdatihU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KolicinaProdatihU)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MvcTrgovac/MvcTrgovac/Views/ProdatiProizvodiU/Edit.cshtml
@model MvcTrgovac.Models.MasterModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Godišnji podaci o količini prodatih duvanskih proizvoda</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.SifraVDP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SifraVDP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SifraVDP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SifraRM, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SifraRM, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SifraRM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SifraJM, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SifraJM, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SifraJM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KolicinaProdatihPP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KolicinaProdatihPP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KolicinaProdatihPP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KolicinaProdatihDP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KolicinaProdatihDP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KolicinaProdatihDP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcTrgovac/MvcTrgovac/Views/ProdatiProizvodiU/Index.cshtml
@model PagedList.IPagedList<MvcTrgovac.Models.MasterModel>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Prodati proizvodi ukupno";
}

@using (Html.BeginForm("Index", "ProdatiProizvodiU", FormMethod.Get, new { @class = "form-inline" }))
{
    <div class="search-background">
        <div class="form-group">
            <i class="glyphicon glyphicon-search"></i>
            @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { @class = "form-control input-sm" })
        </div>
    </div>
}

<div class="headline">
    <h5 class="text-center">Godišnji podaci o količini prodatih duvanskih proizvoda</h5>
</div>

<div class="table-responsive">
    <table class="table">
        <tr>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "ProdatiProizvodiU", FormMethod.Get))
                    {
                        <label for="SifraVDP">
                            @Html.ActionLink("Šifra vrste duvnskog proizvoda", "Index", new { sortOrder = ViewBag.SvdpSortParm, currentFilter = ViewBag.CurrentFilter }, new { @class = "sort-link" })
                            @Html.TextBox("SifraVDP", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "ProdatiProizvodiU", FormMethod.Get))
                    {
                        <label for="SifraRM">
                            @Html.ActionLink("Šifra robne marke", "Index", new { sortOrder = ViewBag.SrmSortParm, currentFilter = ViewBag.CurrentFilter })
                            @Html.TextBox("SifraRM", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "ProdatiProizvodiU", FormMethod.Get))
                    {
                        <label for="SifraJM">
                            @Html.ActionLink("Šifra jedinice mere", "Index", new { sortOrder = ViewBag.SjmSortParm, currentFilter = ViewBag.CurrentFilter })
                            @Html.TextBox("SifraJM", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "ProdatiProizvodiU", FormMethod.Get))
                    {
                        <label for="KolicinaProdatihPP">
                            @Html.ActionLink("Količina prodatih 1.1-30.6", "Index", new { sortOrder = ViewBag.SprodPSortParm, currentFilter = ViewBag.CurrentFilter })
                            @Html.TextBox("KolicinaProdatihPP", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "ProdatiProizvodiU", FormMethod.Get))
                    {
                        <label for="KolicinaProdatihDP">
                            @Html.ActionLink("Količina prodatih 1.7-30.12", "Index", new { sortOrder = ViewBag.SprodDSortParm, currentFilter = ViewBag.CurrentFilter })
                            @Html.TextBox("KolicinaProdatihDP", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "ProdatiProizvodiU", FormMethod.Get))
                    {
                        <label for="KolicinaProdatihU">
                            @Html.ActionLink("Količina prodatih ukupno", "Index", new { sortOrder = ViewBag.SprodUSortParm, currentFilter = ViewBag.CurrentFilter })
                            @Html.TextBox("KolicinaProdatihU", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SifraVDP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SifraRM)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SifraJM)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KolicinaProdatihPP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KolicinaProdatihDP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KolicinaProdatihU)
                </td>
                <td style="min-width: 145px;">
                    <button type="button" onclick="location.href='@Url.Action("Edit", "ProdatiProizvodiU", new { id = item.Id })'" class="btn btn-default">Edit</button> |
                    <button type="button" onclick="location.href='@Url.Action("Delete", "ProdatiProizvodiU", new { id = item.Id })'" class="btn btn-danger">Delete</button>
                </td>
            </tr>
        }

    </table>
</div>

<div class="add-button">
    <button type="button" onclick="location.href='@Url.Action("Create", "ProdatiProizvodiU")'" class="btn btn-info"><i class="glyphicon glyphicon-plus"></i> ADD</button>
</div>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))