MvcTrgovac/MvcTrgovac/Controllers/TrgovacNaVelikoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcTrgovac.Models;
using MvcTrgovac.Repository.IRepository;

namespace MvcTrgovac.Controllers
{
    public class TrgovacNaVelikoesController : Controller
    {
        private readonly ITrgovacNaVelikoRepository _trgovacNaVelikoRepository;

        public TrgovacNaVelikoesController(ITrgovacNaVelikoRepository trgovacNaVelikoRepository)
        {
            this._trgovacNaVelikoRepository = trgovacNaVelikoRepository;
        }
        //private Context db = new Context();

        // GET: TrgovacNaVelikoes
        public ActionResult Index(string searchString, string Datum, string BrojUgovora, string PIB, string naziv)
        {
            List<TrgovacNaVeliko> ListTrgovacNaVeliko = _trgovacNaVelikoRepository.GetAll(searchString, Datum, BrojUgovora, PIB, naziv).ToList();
            return View(ListTrgovacNaVeliko);
        }


        // GET: TrgovacNaVelikoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TrgovacNaVelikoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Datum,BrojUgovora,PIB,Naziv")] TrgovacNaVeliko trgovacNaVeliko)
        {
            if (ModelState.IsValid)
            {
                _trgovacNaVelikoRepository.Create(trgovacNaVeliko);
                return RedirectToAction("Index");
            }

            return View(trgovacNaVeliko);
        }

        // GET: TrgovacNaVelikoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrgovacNaVeliko trgovacNaVeliko = _trgovacNaVelikoRepository.GetById((int)id);
            if (trgovacNaVeliko == null)
            {
                return HttpNotFound();
            }
            return View(trgovacNaVeliko);
        }

        // POST: TrgovacNaVelikoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Datum,BrojUgovora,PIB,Naziv")] TrgovacNaVeliko trgovacNaVeliko)
        {
            if (ModelState.IsValid)
            {
                _trgovacNaVelikoRepository.Edit(trgovacNaVeliko);
                return RedirectToAction("Index");
            }
            return View(trgovacNaVeliko);
        }

        // GET: TrgovacNaVelikoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrgovacNaVeliko trgovacNaVeliko = _trgovacNaVelikoRepository.GetById((int)id);
            if (trgovacNaVeliko == null)
            {
                return HttpNotFound();
            }
            return View(trgovacNaVeliko);
        }

        // POST: TrgovacNaVelikoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _trgovacNaVelikoRepository.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _trgovacNaVelikoRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcTrgovac/MvcTrgovac/Views/TrgovacNaVelikoes/Create.cshtml
@model MvcTrgovac.Models.TrgovacNaVeliko

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TrgovacNaVeliko</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrojUgovora, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojUgovora, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojUgovora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PIB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PIB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PIB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcTrgovac/MvcTrgovac/Views/TrgovacNaVelikoes/Delete.cshtml
@model MvcTrgovac.Models.TrgovacNaVeliko

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TrgovacNaVeliko</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Datum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Datum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrojUgovora)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrojUgovora)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PIB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PIB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MvcTrgovac/MvcTrgovac/Views/TrgovacNaVelikoes/Edit.cshtml
@model MvcTrgovac.Models.TrgovacNaVeliko

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TrgovacNaVeliko</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrojUgovora, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojUgovora, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojUgovora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PIB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PIB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PIB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcTrgovac/MvcTrgovac/Views/TrgovacNaVelikoes/Index.cshtml
@model IEnumerable<MvcTrgovac.Models.TrgovacNaVeliko>

@{
    ViewBag.Title = "Trgovac na veliko";
}

@using (Html.BeginForm("Index", "TrgovacNaVelikoes", FormMethod.Get, new { @class = "form-inline" }))
{
    <div class="search-background">
        <div class="form-group">
            <i class="glyphicon glyphicon-search"></i>
            @Html.TextBox("searchString", null, new { @class = "form-control input-sm" })
        </div>
    </div>
}

<div class="headline">
    <h5 class="text-center">Trgovac na veliko</h5>
</div>

<div class="table-responsive">
    <table class="table">
        <tr>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "TrgovacNaVelikoes", FormMethod.Get))
                    {
                        <label for="Datum">
                            @Html.DisplayNameFor(model => model.Datum)
                            @Html.TextBox("Datum", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "TrgovacNaVelikoes", FormMethod.Get))
                    {
                        <label for="BrojUgovora">
                            @Html.DisplayNameFor(model => model.BrojUgovora)
                            @Html.TextBox("BrojUgovora", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "TrgovacNaVelikoes", FormMethod.Get))
                    {
                        <label for="PIB">
                            @Html.DisplayNameFor(model => model.PIB)
                            @Html.TextBox("PIB", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "TrgovacNaVelikoes", FormMethod.Get))
                    {
                        <label for="naziv">
                            @Html.DisplayNameFor(model => model.Naziv)
                            @Html.TextBox("naziv", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Datum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BrojUgovora)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PIB)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Naziv)
                </td>
                <td style="min-width: 145px;">
                    <button type="button" onclick="location.href='@Url.Action("Edit", "TrgovacNaVelikoes", new { id = item.ID })'" class="btn btn-default">Edit</button> |
                    <button type="button" onclick="location.href='@Url.Action("Delete", "TrgovacNaVelikoes", new { id = item.ID })'" class="btn btn-danger">Delete</button>
                </td>
            </tr>
        }

    </table>
</div>

<div class="add-button">
    <button type="button" onclick="location.href='@Url.Action("Create", "TrgovacNaVelikoes")'" class="btn btn-info"><i class="glyphicon glyphicon-plus"></i> ADD</button>
</div>