MvcTrgovac/MvcTrgovac/Controllers/TrgovacNaMaloesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcTrgovac.Models;
using MvcTrgovac.Repository;
using MvcTrgovac.Repository.IRepository;

namespace MvcTrgovac.Controllers
{
    public class TrgovacNaMaloesController : Controller
    {
        private readonly ITrgovacNaMaloRepository _trgovacNaMaloRepository;

        public TrgovacNaMaloesController(ITrgovacNaMaloRepository trgovacNaMaloRepository)
        {
            this._trgovacNaMaloRepository = trgovacNaMaloRepository;
        }

        //private Context db = new Context();

        // GET: TrgovacNaMaloes
        public ActionResult Index(string searchString, string BrDozvole, string naziv, string adresa, string PIB, string MaticniBroj)
        {
            List<TrgovacNaMalo> ListTrgovacNaMalo = this._trgovacNaMaloRepository.GetAll(searchString, BrDozvole, naziv, adresa, PIB, MaticniBroj).ToList();
            return View(ListTrgovacNaMalo);
        }
        

        // GET: TrgovacNaMaloes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TrgovacNaMaloes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,BrDozvole,Naziv,Adresa,PIB,MaticniBroj")] TrgovacNaMalo trgovacNaMalo)
        {
            if (ModelState.IsValid)
            {
                _trgovacNaMaloRepository.Create(trgovacNaMalo);
                return RedirectToAction("Index");
            }

            return View(trgovacNaMalo);
        }

        // GET: TrgovacNaMaloes/Edit/id
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrgovacNaMalo trgovacNaMalo = _trgovacNaMaloRepository.GetById((int)id);
            if (trgovacNaMalo == null)
            {
                return HttpNotFound();
            }
            return View(trgovacNaMalo);
        }

        // POST: TrgovacNaMaloes/Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,BrDozvole,Naziv,Adresa,PIB,MaticniBroj")] TrgovacNaMalo trgovacNaMalo)
        {
            if (ModelState.IsValid)
            {
                _trgovacNaMaloRepository.Edit(trgovacNaMalo);
                return RedirectToAction("Index");
            }
            return View(trgovacNaMalo);
        }

        // GET: TrgovacNaMaloes/Delete/id
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrgovacNaMalo trgovacNaMalo = _trgovacNaMaloRepository.GetById((int)id);
            if (trgovacNaMalo == null)
            {
                return HttpNotFound();
            }
            return View(trgovacNaMalo);
        }

        // POST: TrgovacNaMaloes/Delete/id
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _trgovacNaMaloRepository.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _trgovacNaMaloRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcTrgovac/MvcTrgovac/Views/TrgovacNaMaloes/Create.cshtml
@model MvcTrgovac.Models.TrgovacNaMalo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TrgovacNaMalo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BrDozvole, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrDozvole, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrDozvole, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PIB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PIB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PIB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaticniBroj, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaticniBroj, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaticniBroj, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcTrgovac/MvcTrgovac/Views/TrgovacNaMaloes/Delete.cshtml
@model MvcTrgovac.Models.TrgovacNaMalo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TrgovacNaMalo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BrDozvole)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrDozvole)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PIB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PIB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaticniBroj)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaticniBroj)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MvcTrgovac/MvcTrgovac/Views/TrgovacNaMaloes/Edit.cshtml
@model MvcTrgovac.Models.TrgovacNaMalo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TrgovacNaMalo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.BrDozvole, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrDozvole, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrDozvole, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PIB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PIB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PIB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaticniBroj, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaticniBroj, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaticniBroj, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcTrgovac/MvcTrgovac/Views/TrgovacNaMaloes/Index.cshtml
@model IEnumerable<MvcTrgovac.Models.TrgovacNaMalo>

@{
    ViewBag.Title = "Trgovac na malo";
}

@using (Html.BeginForm("Index", "TrgovacNaMaloes", FormMethod.Get, new { @class = "form-inline" }))
{
    <div class="search-background">
        <div class="form-group">
            <i class="glyphicon glyphicon-search"></i>
            @Html.TextBox("searchString", null, new { @class = "form-control input-sm" })
        </div>
    </div>
}

<div class="headline">
    <h5 class="text-center">Trgovac na malo</h5>
</div>

<div class="table-responsive">
    <table class="table">
        <tr>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "TrgovacNaMaloes", FormMethod.Get))
                    {
                        <label for="BrDozvole">
                            @Html.DisplayNameFor(model => model.BrDozvole)
                            @Html.TextBox("BrDozvole", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "TrgovacNaMaloes", FormMethod.Get))
                    {
                        <label for="naziv">
                            @Html.DisplayNameFor(model => model.Naziv)
                            @Html.TextBox("naziv", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "TrgovacNaMaloes", FormMethod.Get))
                    {
                        <label for="adresa">
                            @Html.DisplayNameFor(model => model.Adresa)
                            @Html.TextBox("adresa", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "TrgovacNaMaloes", FormMethod.Get))
                    {
                        <label for="PIB">
                            @Html.DisplayNameFor(model => model.PIB)
                            @Html.TextBox("PIB", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th>
                <div class="form-group">
                    @using (Html.BeginForm("Index", "TrgovacNaMaloes", FormMethod.Get))
                    {
                        <label for="MaticniBroj">
                            @Html.DisplayNameFor(model => model.MaticniBroj)
                            @Html.TextBox("MaticniBroj", null, new { @class = "form-control input-sm" })
                        </label>
                    }
                </div>
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BrDozvole)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adresa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PIB)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaticniBroj)
                </td>
                <td style="min-width: 145px;">
                    <button type="button" onclick="location.href='@Url.Action("Edit", "TrgovacNaMaloes", new { id = item.ID })'" class="btn btn-default">Edit</button> |
                    <button type="button" onclick="location.href='@Url.Action("Delete", "TrgovacNaMaloes", new { id = item.ID })'" class="btn btn-danger">Delete</button>
                </td>
            </tr>
        }

    </table>
</div>

<div class="add-button">
    <button type="button" onclick="location.href='@Url.Action("Create", "TrgovacNaMaloes")'" class="btn btn-info"><i class="glyphicon glyphicon-plus"></i> ADD</button>
</div>